apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-gndvfjcx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-gndvfjcx:c12e147a25ffee9c69d6a34561368513df012dcf@sha256:5e71720026d6ab25ab4d2ef5b98348e6d763d8ec85793f68c57cae67ba58e74a
          name: container-image
