apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-gndvfjcx
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-gndvfjcx:3351d3570bcd411bedba29a21580d1c18af9116c@sha256:f7fc3bf0d7023de723388c24fdc76401428d445196a140644cd612ab54594072
        name: container-image  
